---
title: 'Clase 6: Modelos lineales Generalizados: Poisson'
output:
  html_document:
    df_print: paged
---

Los modelos lineales generalizados (GLM) son una clase de modelos estadísticos que se utilizan para describir la relación entre una variable dependiente y una o más variables independientes. A diferencia de los modelos lineales tradicionales, los modelos lineales generalizados no asumen que la relación entre las variables es lineal y permiten la utilización de una distribución de error no normal para la variable dependiente.

Los modelos lineales generalizados se basan en el concepto de un modelo de respuesta generalizado, que es una función matemática que describe la relación entre la variable dependiente y las variables independientes. El modelo de respuesta generalizado incluye una función de enlace, que describe cómo la media de la variable dependiente varía con la variación de las variables independientes, y una función de varianza, que describe cómo la varianza de la variable dependiente varía con la media.

La distribución de Poisson es una distribución de probabilidad discreta que se utiliza para modelar el número de eventos que ocurren en un intervalo de tiempo o un espacio dado. La distribución de Poisson se caracteriza por un solo parámetro, llamado tasa de eventos o tasa de Poisson, que describe la frecuencia esperada de eventos en el intervalo de tiempo o espacio dado.

### Contenido {.tabset .tabset-pills}

Creacion del modeloS

#### Creando modelos candidatos

#### Seleccion de modelo con Criterio de Informacion de Akaike

#### Validacion de modelo

#### Grafico de modelo

#### Distribucion Binomial Negativo

#### Modelo Zero-inflacion



